### GET Crime Prosecution Case Details by URN via APIM
GET {{apim_base_url}}/cases/{{case_urn}}
Authorization: Bearer {{access_token}}
Ocp-Apim-Subscription-Key: {{subscription_key}}

###

### GET Crime Prosecution Case Details by URN via WAF
GET {{waf_base_url}}/cases/{{case_urn}}
Authorization: Bearer {{access_token}}
Ocp-Apim-Subscription-Key: {{subscription_key}}

###